version: "3.9"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ELASTIC_PASSWORD="elastic@123"
      - bootstrap.memory_lock=true
    networks:
      - es-net
    ports:
      - 9200:9200
  
networks:
  es-net:
    driver: bridge
