"""changes_in_power_plug_type

Revision ID: 1973ed1b1a56
Revises: 98f9fa5cd38b
Create Date: 2025-05-23 00:52:24.210216

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1973ed1b1a56"
down_revision: Union[str, None] = "98f9fa5cd38b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "powerplugtype",
        sa.Column("plug_type_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column("powerplugtype", sa.Column("fixed_plug", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("powerplugtype", "fixed_plug")
    op.drop_column("powerplugtype", "plug_type_id")
    # ### end Alembic commands ###
