"""added-here_id-column

Revision ID: 8a7604c47b94
Revises: 2f2a92f29e48
Create Date: 2025-06-13 02:53:03.020731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "8a7604c47b94"
down_revision: Union[str, None] = "2f2a92f29e48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "location",
        sa.Column("here_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "evcharger",
        sa.Column("here_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "evchargerport",
        sa.Column("here_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evchargerport", "here_id")
    op.drop_column("evcharger", "here_id")
    op.drop_column("location", "here_id")
    # ### end Alembic commands ###
