"""modified-location-street-nullable

Revision ID: b1566b196b48
Revises: 828227da6f9d
Create Date: 2025-06-13 06:45:05.203029

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1566b196b48"
down_revision: Union[str, None] = "828227da6f9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "location",
        "street",
        existing_type=sa.String(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "location",
        "street",
        existing_type=sa.String(),
        nullable=False,
    )
    # ### end Alembic commands ###
